import React from "react";
import Link from "next/link";
import { WEB_APPS, MOBILE_APPS } from "@/utils/data";

export const metadata = {
  title: "Projects | Hosna Qasmei",
  description: "Generated by create next app",
};

export default function ProjectsPage() {
  return (
    <main className="mx-auto flex w-full  max-w-3xl flex-1">
      <div className="px-6 pt-24 text-center sm:pt-28 md:px-0 md:text-left">
        <h1 className="bg-gradient-to-r from-purple-600 via-pink-600 to-blue-600 bg-clip-text text-center text-4xl font-bold text-transparent  md:pb-4 md:text-6xl">
          Projects.
        </h1>
        <p className="pb-4 text-center text-xl text-stone-300 ">
          Here are a few side projects I&#39;ve been working on. Check them out!
        </p>
        <section className="mb-6">
          <h1 className="mb-2 text-3xl font-bold text-white">Web Apps</h1>
          <div className="grid grid-cols-1 items-stretch gap-4 sm:grid-cols-2 md:grid-cols-3 ">
            {WEB_APPS.map((item, idx) => {
              return (
                <Link key={idx} href={item.link} target="_blank">
                  <div className="mx-auto flex max-w-md flex-row space-x-4 rounded-lg bg-stone-800 p-4 text-left shadow hover:bg-stone-700 md:flex-col md:space-x-0">
                    <div className="flex items-center justify-center md:justify-start">
                      {item.icon}
                    </div>
                    <div>
                      <h3 className="text-xl font-medium text-stone-100">
                        {item.name}
                      </h3>
                      <p className="mt-1 text-stone-400">{item.description}</p>
                    </div>
                  </div>
                </Link>
              );
            })}
          </div>
        </section>
        <section>
          <h1 className="mb-2 text-3xl font-bold text-white">Mobile Apps</h1>
          <div className="grid grid-cols-1 items-stretch gap-4 sm:grid-cols-2 md:grid-cols-3 ">
            {MOBILE_APPS.map((item, idx) => {
              return (
                <Link key={idx} href={item.link} target="_blank">
                  <div className="mx-auto flex max-w-md flex-row space-x-4 rounded-lg bg-stone-800 p-4 text-left shadow hover:bg-stone-700 md:flex-col md:space-x-0">
                    <div className="flex items-center justify-center md:justify-start">
                      {item.icon}
                    </div>
                    <div>
                      <h3 className="text-xl font-medium text-stone-100">
                        {item.name}
                      </h3>
                      <p className="mt-1 text-stone-400">{item.description}</p>
                    </div>
                  </div>
                </Link>
              );
            })}
          </div>
        </section>
      </div>
    </main>
  );
}
