export const bookList = [
  {
    title: "101 Essays That Will Change the Way You Think",
    authors: "Wiest, Brianna",
  },
  { title: "A Dutiful Boy", authors: "Zaidi, Mohsin" },
  { title: "A Little Life", authors: "Yanagihara, Hanya" },
  { title: "A Man Called Ove", authors: "Backman, Fredrik" },
  { title: "A New Earth", authors: "Eckhart Tolle" },
  { title: "All the Light We Cannot See", authors: "Doerr, Anthony" },
  { title: "Anything You Want", authors: "Sivers, Derek" },
  {
    title: "Aristotle and Dante Dive Into the Waters of the World",
    authors: "Benjamin Alire Sáenz",
  },
  { title: "Atlas of the Heart", authors: "Brené Brown" },
  { title: "Atomic Habits", authors: "Clear, James" },
  { title: "Attached", authors: "Amir Levine, Rachel Heller" },
  { title: "Barking Up the Wrong Tree", authors: "Barker, Eric" },
  { title: "Beyond Good and Evil", authors: "Friedrich Wilhelm Nietzsche" },
  { title: "Bittersweet", authors: "Cain, Susan" },
  { title: "Blindspot", authors: "Mahzarin R. Banaji, Anthony G. Greenwald" },
  { title: "Born a Crime", authors: "Noah, Trevor" },
  { title: "Brave, Not Perfect", authors: "Reshma Saujani" },
  { title: "Braving the Wilderness", authors: "Brené Brown" },
  { title: "Breath", authors: "Nestor, James" },
  { title: "Broken Horses", authors: "Brandi Carlile" },
  { title: "Come as You Are", authors: "Nagoski, Emily" },
  { title: "Crime and Punishment", authors: "Fyodor Dostoyevsky" },
  { title: "Crying in H Mart", authors: "Zauner, Michelle" },
  { title: "Dare to Lead", authors: "Brené Brown" },
  { title: "Daring Greatly", authors: "Brené Brown" },
  { title: "Dark Matter", authors: "Crouch, Blake" },
  { title: "Designing Your Life", authors: "Burnett, Bill; Evans, Dave" },
  { title: "Emotional Agility", authors: "Susan David" },
  { title: "Flowers for Algernon", authors: "Keyes, Daniel" },
  { title: "Forward", authors: "Wambach, Abby" },
  { title: "Girls Can Kiss Now", authors: "Gutowitz, Jill" },
  { title: "Goodbye, Again", authors: "Jonny Sun" },
  { title: "Grit", authors: "Duckworth, Angela" },
  { title: "How High We Go in the Dark", authors: "Nagamatsu, Sequoia" },
  { title: "How to Do the Work", authors: "Nicole LePera" },
  {
    title: "How to Win Friends and Influence People",
    authors: "Dale Carnegie",
  },
  { title: "In the Dream House", authors: "Carmen Maria Machado" },
  { title: "Love Poems", authors: "Neruda, Pablo" },
  { title: "Love is a Dog From Hell", authors: "Bukowski, Charles" },
  { title: "Maybe You Should Talk to Someone", authors: "Lori Gottlieb" },
  { title: "Milk and Honey", authors: "Rupi Kaur" },
  { title: "Open Me Carefully", authors: "Emily Dickinson" },
  { title: "Permission to Feel", authors: "Ph.D. Marc Brackett" },
  { title: "Play Well with Others", authors: "Eric Barker" },
  { title: "Quiet", authors: "Susan Cain" },
  { title: "Recursion", authors: "Crouch, Blake" },
  { title: "Rich Dad, Poor Dad", authors: "Kiyosaki, Robert T." },
  { title: "Rising Strong", authors: "Brené Brown" },
  { title: "Secrets of Divine Love", authors: "Helwa, A." },
  { title: "Self-Compassion", authors: "Neff, Dr. Kristin" },
  { title: "Set Boundaries, Find Peace", authors: "Nedra Glover Tawwab" },
  { title: "Start with Why", authors: "Sinek, Simon" },
  { title: "Sum", authors: "Eagleman, David" },
  { title: "The 100-Year Life", authors: "Gratton, Lynda; Scott, Andrew" },
  {
    title: "The 7 Habits of Highly Effective People",
    authors: "Stephen R. Covey",
  },
  { title: "The Alchemist", authors: "Paulo Coelho" },
  {
    title: "The Art of Happiness",
    authors: "Dalai Lama XIV Bstan-\u02bcdzin-rgya-mtsho, Howard C. Cutler",
  },
  { title: "The Art of Seduction", authors: "Robert Greene" },
  { title: "The Body Keeps the Score", authors: "Bessel A. Van der Kolk" },
  { title: "The Collected Poems of Audre Lorde", authors: "Audre Lorde" },
  { title: "The Complete Poetry", authors: "Angelou, Maya" },
  { title: "The Four Agreements", authors: "Don Miguel Ruiz, Janet Mills" },
  { title: "The Gifts of Imperfection", authors: "Bre\u0148 Brown" },
  { title: "The House in the Cerulean Sea", authors: "Klune, TJ" },
  { title: "The Last Black Unicorn", authors: "Tiffany Haddish" },
  { title: "The Lean Startup", authors: "Ries, Eric" },
  { title: "The Midnight Library", authors: "Haig, Matt" },
  { title: "The Motivation Manifesto", authors: "Brendon Burchard" },
  { title: "The Power of Regret", authors: "Pink, Daniel H." },
  { title: "The Prophet", authors: "Gibran, Kahlil" },
  { title: "The Silent Patient", authors: "Michaelides, Alex" },
  { title: "The Stranger", authors: "Albert Camus" },
  { title: "The Strength in Our Scars", authors: "Sparacino, Bianca" },
  {
    title: "The Untethered Soul (EasyRead Edition)",
    authors: "Singer, Michael A.",
  },
  { title: "The Way of Integrity", authors: "Martha Beck" },
  { title: "Think and Grow Rich", authors: "Hill, Napoleon" },
  { title: "Thinking, fast and slow", authors: "Daniel Kahneman" },
  { title: "Too Perfect", authors: "Allan E. Mallinger, Jeannette De Wyze" },
  { title: "Tuesdays with Morrie", authors: "Mitch Albom" },
  { title: "Unfu*k Yourself", authors: "Gary John Bishop" },
  {
    title: "Unlearn: 101 Simple Truths for a Better Life",
    authors: "Humble the Poet",
  },
  { title: "WOLFPACK", authors: "Abby Wambach" },
  { title: "What Happened to You?", authors: "Oprah Winfrey, Bruce D. Perry" },
  {
    title: "What I Talk about when I Talk about Running",
    authors: "Murakami, Haruki",
  },
  { title: "What Would Frida Do?", authors: "Arianna Davis" },
  { title: "Who Moved My Cheese?", authors: "Spencer Johnson" },
  { title: "Why Won't You Apologize?", authors: "Harriet Lerner" },
  { title: "You Are a Badass", authors: "Jen Sincero" },
  { title: "Zero to One", authors: "Masters, Blake; Thiel, Peter" },
]
