export default function Head() {
  return (
    <>
      <title>Hosna Qasmei</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <script
        async
        defer
        data-website-id="cc8929a7-0c1e-4f05-86e9-0fe251730c57"
        src="https://hosnaqasmei-umami.vercel.app/umami.js"
      ></script>
    </>
  )
}
