import React from "react"
import Content from "@/components/Content"
import { getAllBooksMeta } from "../../lib/mdx"
import { getAllTags } from "../../lib/tags"

export const metadata = {
  title: "Book Notes | Hosna Qasmei",
  description: "Generated by create next app",
}

const BookNotesPage = async () => {
  const books = await getAllBooksMeta("books")
  const tags = await getAllTags()

  return (
    <main className="mx-auto w-full flex max-w-3xl flex-1">
      <div className="flex flex-col space-y-4 py-24 px-6 md:px-0 sm:py-28 md:space-y-4  ">
        <h1 className="text-white text-4xl font-bold md:text-6xl ">
          Book Notes
        </h1>

        <Content books={books} tags={tags} />
      </div>
    </main>
  )
}

export default BookNotesPage
