import React from "react"
import Content from "@/components/Content"
import { getAllBooksMeta } from "../../lib/mdx"
import { getAllTags } from "../../lib/tags"

export const metadata = {
  title: "Book Notes | Hosna Qasmei",
  description: "Generated by create next app",
}

const BookNotesPage = async () => {
  const books = await getAllBooksMeta("books")
  const tags = await getAllTags()

  return (
    <main className="mx-auto flex w-full max-w-3xl flex-1">
      <div className="flex flex-col space-y-4 py-24 px-6 sm:py-28 md:space-y-4 md:px-0  ">
        <h1 className="bg-gradient-to-r from-purple-600 via-pink-600 to-blue-600 bg-clip-text text-center text-4xl font-bold text-transparent  md:pb-4 md:text-6xl">
          Book Notes.
        </h1>

        <Content books={books} tags={tags} />
      </div>
    </main>
  );
}

export default BookNotesPage
